name: Build & Test

on:
  pull_request:
    branches: [main, develop, release/**]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: ['8.0.x', '10.0.x']
    steps:
      - name: Checkout repo (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Clean
        run: dotnet clean BTCPayServer.Plugins.Branta

      - name: Restore dependencies
        run: dotnet restore BTCPayServer.Plugins.Branta --locked-mode

      - name: Build plugin
        run: dotnet build BTCPayServer.Plugins.Branta --no-restore -m:1

      - name: Run Tests
        run: dotnet test BTCPayServer.Plugins.Branta.Tests -m:1